name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Browser to run tests on (chromium, firefox, webkit, all)"
        required: true
        default: "chromium"
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.2-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright smoke tests
        run: |
          if [ "${{ github.event.inputs.browser }}" == "all" ]; then
            npx playwright test --grep @smoke --reporter=html
          else
            npx playwright test --grep @smoke --reporter=html --project=${{ github.event.inputs.browser }}
          fi
