name: Playwright Tests

on:
  workflow_dispatch:        # Manual trigger
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      # Zip report for email
      - name: Zip report
        if: always()
        run: zip -r playwright-report.zip playwright-report

      # Upload report as artifact (optional - for download in GitHub UI)
      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Send email with attached report
      - name: Send email with report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Playwright Test Report"
          to: "manishdandotiya227@gmail.com"
          from: "GitHub Actions <${{ secrets.EMAIL_USER }}>"
          body: |
            Hi Team,

            Please find the attached Playwright Test Report.

            Regards,
            Automation
          attachments: "playwright-report.zip"
